apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitor
spec:
  selector:
    matchLabels:
      app: monitor
  template:
    metadata:
      labels:
        app: monitor
    spec:
      containers:
      - name: monitor
        image: californibrs/monitor-proactivemonitoring  #initial image
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
            
---
apiVersion: v1
kind: Service
metadata:
  name: monitor
spec:
  type: LoadBalancer
  selector:
    app: monitor
  ports:
  - port: 5000 # port from application
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: analyser
spec:
  selector:
    matchLabels:
      app: analyser
  template:
    metadata:
      labels:
        app: analyser
    spec:
      containers:
      - name: analyser
        image: californibrs/analyser-selfdiagnosis #initial image
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: analyser
spec:
  type: LoadBalancer
  selector:
    app: analyser
  ports:
  - port: 5001 # port from application


---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: microcontrollers-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      #Endpoints A-C: ProactiveMonitoring
      - path: /monitoroperationa
        backend:
          serviceName: monitor
          servicePort: 5000
      - path: /monitoroperationb
        backend:
          serviceName: monitor
          servicePort: 5000
      - path: /monitoroperationc
        backend:
          serviceName: monitor
          servicePort: 5000   

        #Endpoints D-F: DynamicMonitoring
      - path: /monitoroperationd
        backend:
          serviceName: monitor
          servicePort: 5000
      - path: /monitoroperatione
        backend:
          serviceName: monitor
          servicePort: 5000
      - path: /monitoroperationf
        backend:
          serviceName: monitor
          servicePort: 5000   
        

        #Endpoints G-I: Selfdiagnosis
      - path: /analyseroperationg
        backend:
          serviceName: analyser
          servicePort: 5001
      - path: /analyseroperationh
        backend:
          serviceName: analyser
          servicePort: 5001
      - path: /analyseroperationi
        backend:
          serviceName: analyser
          servicePort: 5001

        #Endpoints J-L: RealiabilityEstimation
      - path: /analyseroperationj
        backend:
          serviceName: analyser
          servicePort: 5001
      - path: /analyseroperationk
        backend:
          serviceName: analyser
          servicePort: 5001
      - path: /analyseroperationl
        backend:
          serviceName: analyser
          servicePort: 5001
