apiVersion: apps/v1
kind: Deployment
metadata:
  name: selfdiagnosis-deployment
spec:
  selector:
    matchLabels:
      app: selfdiagnosis
  template:
    metadata:
      labels:
        app: selfdiagnosis
    spec:
      containers:
      - name: selfdiagnosis
        image: californibrs/selfdiagnosis-python-version
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: selfdiagnosis-service
spec:
  type: LoadBalancer
  selector:
    app: selfdiagnosis
  ports:
  - port: 5001 # port from application
---